spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dimonn104@gmail.com
    password: Pobeda2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
